### ISSUE TITLE
Update TagAPI to use the scoreboard.

### ISSUE THREAD

**Issue by TheJeterLP** [mbax/TagAPI#10]
TagAPI should use the Scoreboard system from Bukkit, so the skin does not change and the name can be longer than 16 characters using prefix and suffix.
Also TagAPI wouldnt need to be updatet at each new Minecraft version.

**Comment by mbax** [comment]
The entire purpose of TagAPI is to provide a method for entirely changing the nametag for a player. Scoreboards have a different purpose.

I also am the author of the Scoreboard API commit ( https://github.com/Bukkit/Bukkit/commit/6fb1647394289a45b71f442647303d06921b376c ), so this isn't fear/hatred of scoreboards. They just serve a different purpose :)
