### ISSUE TITLE
Not to sure what this means

### ISSUE THREAD

**Issue by saldarkseed** [mbax/TagAPI#17]
28.05 01:54:51 [Server] INFO Using hooks for CraftBukkit v1_7_R3
28.05 01:54:51 [Server] INFO The above (or below, if your log reads in reverse) message DOES NOT mean there is a problem with TagAPI. Don't panic. Just breathe!
28.05 01:54:51 [Server] INFO When I check the version string I get "git-Spigot-1483 (MC: 1.7.9)" which doesn't sound like CraftBukkit to me (Could be wrong!).
28.05 01:54:51 [Server] INFO It looks like you're using a mod, but it's claiming to be "CraftBukkit" when I ask it.
28.05 01:54:51 [Server] WARN Inconsistency found: Potential mod detected. TagAPI may not run properly. Let's try it anyway!
28.05 01:54:51 [Server] INFO Enabling TagAPI v3.0.4

Is this a problem, can i fix it, should i even worry about it?

**Comment by TheMolkaPL** [comment]
You are running your server on Spigot, not CraftBukkit.
Spigot is a fork of CraftBukkit, so please ignore this error.

**Comment by saldarkseed** [comment]
Ok thank you :)

**Comment by mbax** [comment]
TagAPI is written to work with CraftBukkit. When TagAPI loads, it tries to give a warning if it detects it isn't running on that server mod.

The server mod you are using is claiming to be CraftBukkit when asked, though it isn't. TagAPI is warning you that this may be a problem, but it's going to try it out anyway.
