### ISSUE TITLE
Cauldron (MCPC+) support

### ISSUE THREAD

**Issue by ChrisLane** [mbax/TagAPI#18]
I'm not sure what your stance on adding support for modded versions of craftbukkit is but I would certainly like it if this was fixed :)

The error http://paste2.org/PPa9GxZG occurs when running TagAPI v3.0.4 on a Cauldron (MCPC+) 1.7.2 server.

The version of Cauldron that I am using is build 86 http://ci.md-5.net/job/Cauldron/86/

**Comment by mbax** [comment]
Looks like **somebody** completely changed things around again. :3

I'll investigate supporting more systems after Mojang either a) releases 1.8 or b) clarifies on what they'll be doing with regard to skins and 'NPC's

**Comment by ChrisLane** [comment]
Seems fixed
