### ISSUE TITLE
TagAPI doesn't update tags until the player is rerendered

### ISSUE THREAD

**Issue by ghost** [mbax/TagAPI#19]
The tag above a player's head will not update until they are unloaded and reloaded by a client (e.g. walking 10 chunks away and then coming back). This only happens in 1.7.8, 1.7.9, and 1.7.10

**Comment by mbax** [comment]
Link to code?

**Comment by ghost** [comment]
```
@EventHandler(priority=EventPriority.NORMAL)
public void onRespawn(AsyncPlayerReceiveNameTagEvent p_event)
{
    Player t_seen = p_event.getNamedPlayer();

    if((Game.isStarting || Game.isRunning) && Game.alive.contains(t_seen))
        p_event.setTag("");
}
```

Very simple. I know it works, because the tag changes if the player goes out of sight and comes back. However, it does not change on its own. Even hiding and showing the player to the player seeing the tagged player does not make it work.

I also try TagAPI.refreshPlayer() elsewhere in my code, but no dice.

**Comment by mbax** [comment]
refreshPlayer triggers a disappearance and reappearance ;)

Call refreshPlayer after the player's status changes.

**Comment by ghost** [comment]
So I need to call refreshPlayer in the event?

**Comment by mbax** [comment]
The event only fires when the player reappears. Calling refreshPlayer in the event will trigger a hilarious loop where your players are constantly flickering.

**Comment by ghost** [comment]
I don't get it... I call refreshPlayer outside of the event, but it doesn't work.

I get what you're saying, refreshPlayer hides and shows the player. But why does it not update the tag when I call it?

**Comment by mbax** [comment]
If refreshPlayer didn't work I'd have a hundred tickets on this by now. I suspect you're doing something slightly incorrect. Add debug output EVERYWHERE! :)
