### ISSUE TITLE
Can't see skins in 1.7.10

### ISSUE THREAD

**Issue by jackklink** [mbax/TagAPI#21]
While using a 1.7.10 client with Spigot 1.7.10 build #1573, you cannot see skins of players whose names have been adjusted by TagAPI.

For example, using the plugin NameTags. People with white names have skins and people with coloured names are Steve.

This might be a monjang thing that is out of your control, but letting you know here.

**Comment by mbax** [comment]
Known issue as documented on every TagAPI changelog since 1.7.5 ;)

Working on a hacky solution still. Today, in fact.

**Comment by jackklink** [comment]
Sorry about that, but great that you might have a solution!

Also... I always forget to click that CLOSED tab on the github issues tracker. If i had thought of that, i wouldn't have even made this post!

**Comment by jackklink** [comment]
Did you have any luck with your hacky solution? I was thinking about it and wondered if you can somehow use the same protocols that /scoreboard uses to set tag colors? Maybe even make a fake scoreboard somehow. Just a thought.
