### ISSUE TITLE
Players getting kicked when Player Tag is modified

### ISSUE THREAD

**Issue by viddie** [mbax/TagAPI#25]
Hello,
I am currently experiencing some issues with TagAPI when I want to modify some Players name tag. First I thought there was a problem with my code in the AsyncPlayerReceiveNameTagEvent listener, but even when I was doing nothing more than setting the name tag for one player it would disconnect the player seeing the modified name tag. Here is the code I want to use:

```
@EventHandler
public void onSeeNameTag(AsyncPlayerReceiveNameTagEvent event){
    Player p = event.getNamedPlayer();
    System.out.println(event.getTag());
    if(!CommandManager.customNames.containsKey(p)){
        return;
    }
    String tag = CommandManager.customNames.get(p);
    event.setTag(ChatColor.GOLD+tag);
}
```

CommandManager.customNames.containsKey(p) returns a random name generated by iDisguise. The Error can't be caused by iDisguise, because with the scoreboard and the chat name it works fine.
I hope you can help me out,
sincerely, viddie

**Comment by mbax** [comment]
What do they disconnect with?

**Comment by viddie** [comment]
I do know that they disconnected with the reason NullPointerException, but somehow it is working now. I have changed nothing, but it works :D
Thank you anyway for the fast reply, not many supports do have this service. Keep it up! 
Sincerely, viddie

**Comment by mbax** [comment]
Woohoo.
