### ISSUE TITLE
MCStats errors

### ISSUE THREAD

**Issue by aarontwf** [mbax/TagAPI#3]
MCStats needs to be updated to R6 prevent this error in the console:
<code>[Metrics] Server returned HTTP response code: 504 for URL: http://mcstats.org/report/TagAPI</code>

I would suggest using it as a dependency with the maven shade plugin instead of having it inside the API (unless you make changes to it) so that it updates automatically.

**Comment by mbax** [comment]
https://github.com/KittehOrg/TagAPI/commit/37a866e5272f0835abb99c450e16bf7a7116eb46
